### ISSUE TITLE
How to setup eslint-plugin-graphql with graphql-tag when used as webpack-loader

### ISSUE THREAD

**Issue by eigenmannmartin** [apollostack/eslint-plugin-graphql#25]
I'm using [graphql-tag as a webpack-loader](https://github.com/apollostack/graphql-tag#webpack-preprocessing) and I can't get the linter working for my *.gql files.

Surely I do have to configure eslint to lint .qgl files. Maybe someone has already tried it and can help me?
I can't find a solution.

**Comment by stubailo** [comment]
I think we would need to update the plugin to add support for a `.graphql` file extension: http://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins

I'd gladly accept a PR for this!

**Comment by eigenmannmartin** [comment]
@stubailo I did open a PR #26 
I am pretty sure it needs more work. Maybe you can help me on this matter?

cheers
