### ISSUE TITLE
Better support for GraphQL literal files

### ISSUE THREAD

**Issue by jtmthf** [apollostack/eslint-plugin-graphql#35]
As it stands, it's not very well documented on how to setup parsing of literal files. After some digging through the source, I was able to get the plugin working for literal files by setting tagName to "ESLintPluginGraphQLFile". Could there perhaps be an `internal` env that would automatically default to this tag name.

Thanks,

**Comment by stubailo** [comment]
Hi! The graphql literal linting was added recently in a PR. Would you mind sending an improvement to the library to make it easier to use? Let me know if I can help.

**Comment by jnwng** [comment]
looks like this was resolved, please re-open if not!
